test: try to fix idempotency check
Signed-off-by: Utku Ozdemir <uoz@protonmail.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -71,7 +71,8 @@ jobs:
         working-directory: tests/
         run: |
           poetry run ansible-playbook -i inventories/local test.yml |& tee output.txt
-          bash -c '! grep -w "changed=[1-9]" output.txt'
+          grep -w "changed=[1-9]" output.txt && echo "Idempotency check failed" && exit 1
+          echo "Idempotency check passed"
 
       - name: Prepare secrets
         run: |
